name: Publicar Imagen en GitHub Packages y Desplegar Swarm

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read
  packages: write

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3. Instalar dependencias en la Action
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Iniciar sesion en GitHub Packages (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: arszaruma-gif
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 5. Validar y Publicar la imagen Docker en tu perfil
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/arszaruma-gif/calculadora:latest

      - name: Probar la SSH en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERS }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Probando conexion ssh el vps"
            mkdir -p ~/landinga
            touch ~/landinga/quintoa.txt

      - name: Pasar archivos desde git al VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERS }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "stack.yml,docker-compose.yml" # Envía los archivos que manejen tu stack
          target: "/home/${{ secrets.VPS_USERS }}/landinga"

      - name: Despliegue de los servicios
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERS }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "✅ Desplegando servicios"        
            cd ~/landinga

            # Autenticación segura y descarga de la imagen de la calculadora
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u arszaruma-gif --password-stdin
            docker pull ghcr.io/arszaruma-gif/calculadora:latest

            echo "==> Desplegando stack..."
            docker stack deploy -c stack.yml calculadora
